### ISSUE TITLE
good work , some errors on Godot Engine v4.3.dev1

### ISSUE THREAD

**Issue by catafest** [Calinou/godot-rendering-tests#1]
Godot Engine v4.3.dev1.official.9d1cbab1c - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 536.23 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce GTX 950
I got these errors:
![image](https://github.com/Calinou/godot-rendering-tests/assets/2210118/e4091955-ed7d-422d-a85a-aa67be5905f6)

**Comment by Calinou** [comment]
Fixed by https://github.com/Calinou/godot-rendering-tests/commit/185d5c3f9c841dbe9668910cfeef06c7cacc512e and https://github.com/Calinou/godot-rendering-tests/commit/fb039bf0c8564bb67464e6e5795d296448bf5d3e.
